server:
  port: 9094

spring:
  application:
    name: BookingPlatform-SeatSelector

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka
