server:
  port: 9092

spring:
  application:
    name: BookingPlatform-BrowseMovie

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka



