server:
  port: 9093

spring:
  application:
    name: BookingPlatform-BookingOrder

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka